---
- name: "Nginx Installation"
  become: yes
  hosts: prod:proxy:staging
  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
    - name: "Install epel-release"
      yum:
        name: epel-release
        state: present
    - name: "Install nginx"
      yum:
        name: nginx
        state: latest
    - name: "start nginx"
      service:
        name: nginx
        state: started
        enabled: yes
    - name: "Allow http connection"
      firewalld:
        service: "http"
        permanent: yes
        state: "enabled"
...