all:
  hosts:
    client1: 
      ansible_host: 192.168.99.11
      ansible_user: vagrant 
      ansible_password: vagrant 
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    client2: 
      ansible_host: 192.168.99.12
      ansible_user: vagrant 
      ansible_password: vagrant 
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

#ou encore

#all:
#  hosts:
#    192.168.99.11: # A remplacer par l'IP de votre machine cible
#      ansible_user: vagrant 
#      ansible_password: vagrant 
#      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
#    192.168.99.12: # A remplacer par l'IP de votre machine cible
#      ansible_user: vagrant 
#      ansible_password: vagrant 
#      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'




